### ISSUE TITLE
Password Generator: Allow Configuring Exact Charset

### ISSUE THREAD

**Issue by realsimon** [padlock/padlock#43]
Some sites/apps don't allow "?", "/", etc. in passwords, but at the same require characters other then letters and numbers. It would be nice to be able to configure this.
thank you!

**Comment by MaKleSoft** [comment]
Thanks for the suggestion! I'll look into it.

**Comment by MaKleSoft** [comment]
Put it in the backlog. Not high-priority but definitely a legitimate enhancement.

**Comment by MaKleSoft** [comment]
I've thought about this for a bit and I can't really think of a way to implement this without adding clutter to the existing UI. Since this is a fairly rare use case imo, I don't think it's too much of an inconvenience for users to simply edit out unwanted character afterwards. Closing this as "won't fix". Sorry!
